### ISSUE TITLE
 TXT for _acme-challenge.example.com is not found by the lambda function during verification

### ISSUE THREAD

**Issue by dulshand** [RaduLupan/terraform-rdgateway-aws#1]
Lupan,
I am working on the configuration as suggested by you. I am in step 4. I am trying to get the letsencrypt.org certs. I can see that it is attempting to verify the challenge in TXT record. But it gives the below error. I believe this is supposed to have been created by the python script. This is the error which I have in cloudwatch logs.

letsencrypt.org DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.com - check that a DNS record exists for this domain
letsencrypt.org forums say that this record has to be dynamically created by the client script which I believe is in the code. I can see that challenges are being cleared at the end of the script execution. What could be the reason.
Please note that the example.com in this error message is made up. In the actual error message I have a valid domain name registered in Route 53.
Appreciate if you can tell me how to fix this issue.

**Comment by dulshand** [comment]
some more details on the error. Please note that I put example.com in place of the actual domain name.

[DEBUG]	2022-04-20T20:41:08.383Z	9f8da28a-8e83-484e-8686-a50e547353fa	Encountered exception:
Traceback (most recent call last):
  File "/var/task/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(aauthzrs, resp, best_effort)
  File "/var/task/certbot/auth_handler.py", line 155, in _respond
    self._poll_challenges(aauthzrs, chall_update, best_effort)
  File "/var/task/certbot/auth_handler.py", line 226, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
certbot.errors.FailedChallenges: Failed authorization procedure. example.com (dns-01): urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.com - check that a DNS record exists for this domain

**Comment by dulshand** [comment]
I resolved this issue. when I started the process I did not have the domain name registered. The terraform script requested only the hosted zone name. So I created a hosted zone manually. It did not have a domain name associated. I realized that I need a domain name. once domain name was registered it created another hosted zone with the same name. The script was still hitting the first hosted zone and failed. I deleted the manually created hosted zone while leaving the one created by the registar. So it works now.

**Comment by RaduLupan** [comment]
@dulshand  Thank you for trying out the solution. I am glad to hear that you have figured it out. I have now added the domain purchase in the prerequisites section in the README file. I realize now that pointing your domain to AWS Nameservers in Route 53 is not covered here but critical for the solution to work.
Thanks again and enjoy your free certs!

**Comment by RaduLupan** [comment]
Closing issue since problem is resolved after domain was purchased.
